# -*- coding: utf-8 -*-
"""highway-planning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/eleurent/highway-env/blob/master/scripts/highway_planning.ipynb

# Behavioural Planning for Autonomous Highway Driving

We plan a trajectory using the _Optimistic Planning for Deterministic systems_ ([OPD](https://hal.inria.fr/hal-00830182)) algorithm.

##  Setup

We first import useful modules for the environment, agent, and visualization.
"""

# Environment
# !pip install highway-env
import gym
import highway_env
#
# # Agent
# !pip install git+https://github.com/eleurent/rl-agents#egg=rl-agents
from rl_agents.agents.common.factory import agent_factory

# Visualisation
import sys
from tqdm.notebook import trange
# !git clone https://github.com/eleurent/highway-env.git
# !pip install gym pyvirtualdisplay
# !apt-get install -y xvfb python-opengl ffmpeg
sys.path.insert(0, './highway-env/scripts/')
from scripts.utils import record_videos, capture_intermediate_frames

"""## Run an episode"""

# Make environment
env = gym.make("highway-v0")
env = record_videos(env)
obs, done = env.reset(), False
capture_intermediate_frames(env)

# Make agent
agent_config = {
    "__class__": "<class 'rl_agents.agents.tree_search.deterministic.DeterministicPlannerAgent'>",
    "env_preprocessors": [{"method":"simplify"}],
    "budget": 50,
    "gamma": 0.7,
}
agent = agent_factory(env, agent_config)

# Run episode
for step in trange(env.unwrapped.config["duration"], desc="Running..."):
    action = agent.act(obs)
    obs, reward, done, info = env.step(action)
    
env.close()
# show_videos()

